import { Button, Container } from "@mui/material";
import { FaHome } from "react-icons/fa";
import { FaBolt } from "react-icons/fa";
import { FaQrcode } from "react-icons/fa";
import { FaList } from "react-icons/fa";
import { FaUser } from "react-icons/fa";
import { NavLink, Route, Routes } from "react-router-dom";
import { Account } from "./pages/Account/Account";
import "../src/Main.css";
import * as React from "react";
import { styled } from "@mui/material/styles";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import IconButton from "@mui/material/IconButton";
import Paper from "@mui/material/Paper";
import Fab from "@mui/material/Fab";
import List from "@mui/material/List";
import ListItemButton from "@mui/material/ListItemButton";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import ListItemText from "@mui/material/ListItemText";
import ListSubheader from "@mui/material/ListSubheader";
import Avatar from "@mui/material/Avatar";
import MenuIcon from "@mui/icons-material/Menu";
import AddIcon from "@mui/icons-material/Add";
import SearchIcon from "@mui/icons-material/Search";
import MoreIcon from "@mui/icons-material/MoreVert";
import { Home } from "./pages/home/Home";
import { Active } from "./pages/Active/Active";
import { ScanQR } from "./pages/ScanQR/ScanQR";
import { Orders } from "./pages/Order/Order";
import { GrLinkPrevious } from "react-icons/gr";
const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === "dark" ? "#1A2027" : "#f7f7f7",
  ...theme.typography.body2,
  color: theme.palette.text.secondary,
}));

const messages = [
  {
    id: 1,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 2,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/avatar/1.jpg",
  },
  {
    id: 3,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person: "/static/images/avatar/2.jpg",
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person: "/static/images/avatar/3.jpg",
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person: "/static/images/avatar/4.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: "/static/images/avatar/1.jpg",
  },
];

const StyledFab = styled(Fab)({
  position: "absolute",
  zIndex: 1,
  top: -30,
  left: 0,
  right: 0,
  margin: "0 auto",
});

export default function MainiShare() {
  return (
    <React.Fragment>
      <CssBaseline />
      <Container
        maxWidth={"xs"}
        sx={{
          padding: 0,
          height: "100vh",
          borderRadius: 0,
          borderInline: { sm: "0.5px solid gray", xs: "none" },
        }}
      >
        <AppBar
          position="fixed"
          sx={{ backgroundColor: "inherit" }}
          elevation={0}
        >
          <Container
            maxWidth={"xs"}
            sx={{ borderInline: { sm: "0.5px solid gray", xs: "none" } }}
          >
            <Toolbar
              component={Paper}
              sx={{ padding: 0, marginX: "-24px", borderRadius: 0 }}
              elevation={0}
            >
              <Box
                sx={{
                  display: "flex",
                  justifyContent: { sm: "space-between", xs: "space-around" },
                  width: "100%",
                }}
              >
                <IconButton>
                  <GrLinkPrevious size={19} />
                </IconButton>
                <Typography marginTop={"5px"}>iShares</Typography>
                <Typography>
                  <IconButton>
                    <GrLinkPrevious size={19} />
                  </IconButton>
                </Typography>
              </Box>
            </Toolbar>
          </Container>
        </AppBar>
        <Toolbar />
        <Item
          sx={{
            padding: 3,
            marginX: { xs: "0px", sm: "-24px" },
            height: "100%",
          }}
        >
          <Box>
            <Routes>
              <Route path="/" element={<Home />} />
              <Route path="/Active" element={<Active />} />
              <Route path="/ScanQR" element={<ScanQR />} />
              <Route path="/Orders" element={<Orders />} />
              <Route path="/Account" element={<Account />} />
            </Routes>
          </Box>
        </Item>
      </Container>
      <AppBar
        position="fixed"
        sx={{ top: "auto", bottom: 0, backgroundColor: "inherit" }}
        elevation={0}
      >
        <Container maxWidth={"xs"}>
          <Toolbar
            component={Paper}
            sx={{ marginX: "-24px", borderRadius: 0 }}
            elevation={0}
          >
            <Box
              sx={{
                display: "flex",
                justifyContent: { xs: "space-evenly", sm: "space-between" },
                width: "100%",
              }}
            >
              <Button
                color="inherit"
                aria-label="open drawer"
                component={NavLink}
                to={"/"}
              >
                <Box
                  sx={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                  }}
                >
                  <FaHome size={22} />
                  <Typography sx={{ fontSize: "10px", marginTop: 1 }}>
                    Home
                  </Typography>
                </Box>
              </Button>
              <Button color="inherit" component={NavLink} to={"/Active"}>
                <Box
                  sx={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                  }}
                >
                  <FaBolt size={22} />
                  <Typography sx={{ fontSize: "10px", marginTop: 1 }}>
                    Active
                  </Typography>
                </Box>
              </Button>
              <Button color="inherit" component={NavLink} to={"/ScanQR"}>
                <Box
                  sx={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                  }}
                >
                  <FaQrcode size={22} />
                  <Typography sx={{ fontSize: "10px", marginTop: 1 }}>
                    Scan QR
                  </Typography>
                </Box>
              </Button>
              <Button color="inherit" component={NavLink} to={"/Orders"}>
                <Box
                  sx={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                  }}
                >
                  <FaList size={22} />
                  <Typography sx={{ fontSize: "10px", marginTop: 1 }}>
                    Orders
                  </Typography>
                </Box>
              </Button>
              <Button color="inherit" component={NavLink} to={"/Account"}>
                <Box
                  sx={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                  }}
                >
                  <FaUser size={22} />
                  <Typography sx={{ fontSize: "10px", marginTop: 1 }}>
                    Accounts
                  </Typography>
                </Box>
              </Button>
            </Box>
          </Toolbar>
        </Container>
      </AppBar>
    </React.Fragment>
  );
}

// export default function MainiShare() {
//   return (
//     <React.Fragment>
//       <Container maxWidth={"xs"}>
//         <CssBaseline />
//         <Paper elevation={0}>
//           <Box>
//             <Routes>
//               <Route path="/" element={<Account />} />
//               <Route path="/Active" element={<Account />} />
//               <Route path="/ScanQR" element={<Account />} />
//               <Route path="/Orders" element={<Account />} />
//               <Route path="/Account" element={<Account />} />
//             </Routes>
//           </Box>

//         </Paper>
//       </Container>
//     </React.Fragment>
//   );
// }
